version: '3.4'

services:
  js-sample-ga-writter-mvc:
    image: jssamplegawrittermvc:dev
    container_name: js-sample-ga-writter-mvc
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "js-sample-ga-writter-mvc"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/olhalahutina/Documents/GitHub/js-google-analytic-sample/js-sample-ga-writter-mvc:/app
      - /Users/olhalahutina/Documents/GitHub/js-google-analytic-sample:/src
      - /Users/olhalahutina/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/olhalahutina/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/js-sample-ga-writter-mvc.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true